---
- name: create user
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"
    groups: sudo
    append: yes
    create_home: yes
    shell: /bin/bash
  loop: "{{ users }}"

- name: add config file
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "/home/{{ item.name }}/.gitconfig"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0600'
  loop: "{{ users }}"

- name: add SSH directory
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0700'
  loop: "{{ users }}"

- name: deploy authorized_keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', 'files/authorized_keys') }}"
  loop: "{{ users }}"