$ANSIBLE_VAULT;1.1;AES256
61333065656338383930656564353031336639303232356162306132333737633565313263343037
6337373335613738616464306537653961396431643066650a363263643561373764393336343063
32333664323036303336653735653530616237643039626236633433356233656539663930396534
3339373435383935370a643166623863316430643438646162333331396366383739623761333432
35613339613065666636623338336539633334353035323832366561333136393938
