#SPDX-License-Identifier: MIT-0
---
# defaults file for user
users: 
  - name: nikita1
    password: "1234"
    groups: sudo
  - name: nikita2  
    password: "1234"
    groups: sudo
  - name: nikita3
    password: "1234"
